### Post time segments
POST http://{{host}}/segments
Accept: application/json
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "payload": [
    {
      "id": 1,
      "startTimestamp": "2025-03-07_02:34:37",
      "endTimestamp": "2025-03-07_17:42:26",
      "category": {
        "id": 1,
        "name": "Работа",
        "color": "#ffffff",
        "icon": "some.ico"
      }
    },
    {
      "id": 3,
      "startTimestamp": "2025-03-07_17:45:31",
      "category": {
        "id": 1,
        "name": "Работа",
        "color": "#ffffff",
        "icon": "some.ico"
      }
    }
  ],
  "details": "Запрос выполнен успешно"
}