server:
  port: 8080
spring:
  application:
    name: chronofocus-backend
  datasource:
    url: jdbc:h2:file:./chronofocus;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
  jackson:
    default-property-inclusion: non-null
    visibility:
      field: any
jwt:
  secret:
    access-expiration: 3300 # token expiration in seconds
    refresh-expiration: 2592000
    access: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
    refresh: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==

#springdoc:
#  api-docs.path: /api-docs
#  swagger-ui.path: /swagger-ui.html
#  swagger-ui.url: /api/__openapi.yaml

logging:
  level:
    root: INFO
    ru.k4nk.chronofocus: INFO
    org.hibernate.SQL: WARN
    org.springframework: INFO
    org.springframework.security.web.access: INFO
    org.springframework.orm.jpa: info
    org.springframework.transaction: info
app:
  version:  "@project.version@"
  promo-sing-up: promoSingUp